version: '3.8'

services:
  mongodb:
    build: ./mongodb
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017/TODO_List_DB"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - backend

volumes:
  mongodb_data:
